---
version: "2"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/piwigo:/config
    ports:
      - 3005:80
    networks:
      - homestack
    restart: unless-stopped
    depends_on: 
      - piwigo-db
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/grocy:/config
    ports:
      - 3006:80
    networks:
      - homestack
    restart: unless-stopped
  lazy-librarian:
    image: linuxserver/lazylibrarian
    container_name: lazy-librarian
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/lazy_librarian/data:/config
      - /mnt/storage/lazy_librarian/downloads:/downloads
      - /mnt/storage/lazy_librarian/books:/books
    ports:
      - 3007:5299
    networks:
      - homestack
    restart: unless-stopped
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - GUID=1000
      - UMASK_SET=<022>
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/deluge/config:/config
      - /mnt/storage/deluge/downloads:/downloads
    restart: unless-stopped
  tt-rss:
    image: linuxserver/tt-rss
    container_name: tt-rss
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/tt-rss:/config
    ports:
      - 3010:80
    networks:
      - homestack
    restart: unless-stopped
    depends_on: 
      - tt-db
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/heimdall:/config
    ports:
      - 3013:80
      - 3014:443
    networks:
      - homestack
    restart: unless-stopped
  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - TZ=America/Los_Angeles
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - ServerIP=192.168.10.75
      - VIRTUAL_HOST=pihole.ct.net
    volumes:
      - /mnt/storage/pihole/pihole:/etc/pihole/
      - /mnt/storage/pihole/dnsmasq:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    networks:
      - homestack
    restart: unless-stopped
  tt-db:
    image: hypriot/rpi-mysql
    container_name: tt-db
    environment:
      - MYSQL_ROOT_PASSWORD=thisisuttergarbo
      - MYSQL_DATABASE=ttrss
      - MYSQL_USER=ttrss_user
      - MYSQL_PASSWORD=ttrsspassword
    volumes:
      - /mnt/storage/mysql/tt-db:/var/lib/mysql
    ports:
      - 3011:3306
    networks:
      - homestack
    restart: unless-stopped
  piwigo-db:
    image: hypriot/rpi-mysql
    container_name: piwigo-db
    environment:
      - MYSQL_ROOT_PASSWORD=thisisuttergarbo
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo_user
      - MYSQL_PASSWORD=piwigodbpassword
    volumes:
      - /mnt/storage/mysql/piwigo-db:/var/lib/mysql
    ports:
      - 3012:3306
    networks:
      - homestack
    restart: unless-stopped

networks:
  homestack:
