---
version: "2"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/piwigo:/config
    ports:
      - 3005:80
    networks:
      - homestack
    restart: unless-stopped
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/grocy:/config
    ports:
      - 3006:80
    networks:
      - homestack
    restart: unless-stopped
  lazy-librarian:
    image: linuxserver/lazylibrarian
    container_name: lazy-librarian
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/lazy_librarian/data:/config
      - /mnt/storage/lazy_librarian/downloads:/downloads
      - /mnt/storage/lazy_librarian/books:/books
    ports:
      - 3007:5299
    networks:
      - homestack
    restart: unless-stopped
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - GUID=1000
      - UMASK_SET=<022>
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/deluge/config:/config
      - /mnt/storage/deluge/downloads:/downloads
    restart: unless-stopped
  tt-rss:
    image: linuxserver/tt-rss
    container_name: tt-rss
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/tt-rss:/config
    ports:
      - 3010:80
    networks:
      - homestack
    restart: unless-stopped
  dokuwiki:
    image: jesnor/rpi-dokuwiki
    container_name: dokuwiki
    volumes:
      - /mnt/storage/dokuwiki/data:/dokuwiki/data
      - /mnt/storage/dokuwiki/conf:/dokuwiki/conf
      - /mnt/storage/dokuwiki/lib/plugins:/dokuwiki/lib/plugins
      - /mnt/storage/dokuwiki/lib/tpl:/dokuwiki/lib/tpl
    ports:
      - 3011:80
    networks:
      - homestack
    restart: unless-stopped

networks:
  homestack:
